server {
    listen 7860;
    root /usr/share/nginx/html;
    index main.html index.html;

    location / {
        try_files $uri $uri/ /main.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|map|gz)$ {
        expires 1d;
        add_header Cache-Control "public";
    }
}
